### ISSUE TITLE
Wrong redirects

### ISSUE THREAD

**Issue by lordmathis** [Rafase282/URL-Shortener#1]
Sometimes your implementation redirects to a wrong website. For example, if for `http://www.example.com` I get short URL `https://little-url.herokuapp.com/3000` and then I navigate to that URL it redirects me to a completely different website. This is probably because you don't check for already existing short URLs in the database so that same one will be saved for multiple original URLs and then it will redirect to the first one it finds.

**Comment by Rafase282** [comment]
I just confirmed the bug. You are also right on what the issue is. Thanks for reporting it.
If you would like to submit a fix feel free to. Otherwise, it might take me a bit to get around to it for the time being.
